name: Github Table Generator

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */3 * * *'
  push:
    branches:
      - master
    paths:
      - README_template.md
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml pytablewriter
    - name: Upload PS Assets to Discord
      run: |
        python github_update_readme.py ${{ secrets.DC_TOKEN }}
        echo "UPDATE_C=$(if [[ $(git status -s README.md) ]]; then echo 1; else echo 0; fi)" >> $GITHUB_ENV
    - name: Display Changes
      run: echo $env.UPDATE_C
    - name: Commit README.md
      if: env.UPDATE_C==1
      run: |
        git config --global user.name "README Updater"
        git config --global user.email "37000563+flok@users.noreply.github.com"
        git add README.md
        git commit -m "Update README.md with new supported games"
        git push
